config/routes.rb
InnovationFund::Application.routes.draw do
  devise_for :admins
  resources :applications
  get 'applications/new', as: :new_applications

  get 'apply' => 'applications#new_static'
  get 'applyonline' => 'applications#new'

  root 'landing#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application.rb
class Application < ActiveRecord::Base
  validates_presence_of :email, :project_summary, :problem, :solution, :name
  validates_presence_of :funding_history, :key_financials, :team, :target_market
  validates_presence_of :value_proposition, :technology, :competitive_advantage
  validates_presence_of :business_model, :milestones_and_funding_uses
  validates_presence_of :progress_summary, :team_skills, :market_analysis
  validates_presence_of :risks

  uniqueness_error_message = "has already been used on an application. Did you already apply once?"
  validates_uniqueness_of :email, message: uniqueness_error_message
  validates_uniqueness_of :name, message: uniqueness_error_message
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  include ApplicationsHelper
  before_action :set_application, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, except: [:new, :create, :new_static]

  # GET /applications
  # GET /applications.json
  def index
    @applications = Application.all
  end

  # GET /applications/1
  # GET /applications/1.json
  def show
  end

  # GET /applications/new
  def new
    @application = Application.new
  end

  def new_static
    @application = Application.new
  end

  # GET /applications/1/edit
  def edit
  end

  # POST /applications
  # POST /applications.json
  def create
    @application = Application.new(application_params)

    respond_to do |format|
      if @application.save
        format.html {
          send_simple_message(@application)
          redirect_to root_path, notice: 'Application was successfully created.'
        }
        format.json { render action: 'show', status: :created, location: @application }
      else
        format.html { render action: 'new' }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applications/1
  # PATCH/PUT /applications/1.json
  def update
    respond_to do |format|
      if @application.update(application_params)
        format.html { redirect_to @application, notice: 'Application was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applications/1
  # DELETE /applications/1.json
  def destroy
    @application.destroy
    respond_to do |format|
      format.html { redirect_to applications_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_application
      @application = Application.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def application_params
      params.require(:application).permit(:video_link, :project_summary, :problem, :solution, :name, :email, :funding_history, :key_financials, :team, :target_market, :value_proposition, :technology, :competitive_advantage, :business_model, :milestones_and_funding_uses, :progress_summary, :team_skills, :market_analysis, :risks)
    end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper

# send email using mailgun
  def send_simple_message(application);
    message = ""
    if application.name?
      message = message + "name:\n"
      message = message + application.name + "\n"
    end
    if application.email?
      message = message + "email:\n"
      message = message + application.email + "\n"
    end
    if application.video_link?
      message = message + "video link:\n"
      message = message + application.video_link + "\n"
    end
    if application.project_summary?
      message = message + "project summary:\n"
      message = message + application.project_summary + "\n"
    end
    if application.problem?
      message = message + "problem:\n"
      message = message + application.problem + "\n"
    end
    if application.solution?
      message = message + "solution:\n"
      message = message + application.solution + "\n"
    end
    if application.funding_history?
      message = message + "funding history:\n"
      message = message + application.funding_history + "\n"
    end
    if application.key_financials?
      message = message + "key financials:\n"
      message = message + application.key_financials + "\n"
    end
    if application.team?
      message = message + "team:\n"
      message = message + application.team + "\n"
    end
    if application.target_market?
      message = message + "target market:\n"
      message = message + application.target_market + "\n"
    end
    if application.value_proposition?
      message = message + "value proposition:\n"
      message = message + application.value_proposition + "\n"
    end
    if application.technology?
      message = message + "technology:\n"
      message = message + application.technology + "\n"
    end
    if application.competitive_advantage?
      message = message + "competitive advantage:\n"
      message = message + application.competitive_advantage + "\n"
    end
    if application.business_model?
      message = message + "business model:\n"
      message = message + application.business_model + "\n"
    end
    if application.milestones_and_funding_uses?
      message = message + "milestones and funding_uses:\n"
      message = message + application.milestones_and_funding_uses + "\n"
    end
    if application.progress_summary?
      message = message + "progress summary:\n"
      message = message + application.progress_summary + "\n"
    end
    if application.team_skills?
      message = message + "team skills:\n"
      message = message + application.team_skills + "\n"
    end
    if application.market_analysis?
      message = message + "market analysis:\n"
      message = message + application.market_analysis + "\n"
    end
    if application.risks?
      message = message + "risks:\n"
      message = message + application.risks + "\n"
    end
    RestClient.post "https://api:#{ENV["MAILGUN_API"]}"\
    "@api.mailgun.net/v2/sandboxdf3755ef3af8417caa3e242e2a3e8ac8.mailgun.org/messages",
  :from => "Mailgun Sandbox <postmaster@sandboxdf3755ef3af8417caa3e242e2a3e8ac8.mailgun.org>",
  :to => "Tony Xie <txie145@gmail.com>",
  :subject => "Hello Tony Xie",
  :text => "#{message}"
  end

end

app/helpers/landing_helper.rb
module LandingHelper
end

app/views/applications/_form.html.haml
= form_for @application, class: "form" do |f|
  .form-group
    %label Company name
    = f.text_field :name, class: "form-control"
  .form-group
    = f.label :email, "Main contact email"
    = f.email_field :email, class: "form-control"
  .form-group
    = f.label :video_link, "Optional link to 2-minute pitch on Youtube"
    = f.text_field :video_link, class: "form-control"
  .form-group
    = f.label :project_summary, "Project summary in 100 words"
    = f.text_area :project_summary, class: "form-control", rows: 5
  .form-group
    = f.label :problem, "What problem are you trying to solve?"
    = f.text_area :problem, class: "form-control", rows: 3
  .form-group
    = f.label :solution, "What is your solution?"
    = f.text_area :solution, class: "form-control", rows: 3
  .form-group
    = f.label :progress_summary, "Provide a detailed description of the progress you made so far in the business (max 500 words)."
    = f.text_area :progress_summary, class: "form-control", rows: 12
  .form-group
    = f.label :key_financials, "What are your key financials?"
    = f.text_area :key_financials, class: "form-control", rows: 12
  .form-group
    = f.label :team, "Tell us what we should know about your team, that is Penn affliations and other qualifications."
    = f.text_area :team, class: "form-control", rows: 12
  .form-group
    = f.label :team_skills, "What kind of unique skills does your team bring?"
    = f.text_area :team_skills, class: "form-control", rows: 12
  .form-group
    = f.label :target_market, "What is your target market?"
    = f.text_area :target_market, class: "form-control", rows: 3
  .form-group
    = f.label :business_model, "What is your business model?"
    = f.text_area :business_model, class: "form-control", rows: 12
  .form-group
    = f.label :value_proposition, "What is your unique value proposition?"
    = f.text_area :value_proposition, class: "form-control", rows: 3
  .form-group
    = f.label :market_analysis, "Give an analysis of your competitors."
    = f.text_area :market_analysis, class: "form-control", rows: 12
  .form-group
    = f.label :technology, "What types of technology are you leveraging?"
    = f.text_area :technology, class: "form-control", rows: 3
  .form-group
    = f.label :competitive_advantage, "What is your competitive advantage against these competitors?"
    = f.text_area :competitive_advantage, class: "form-control", rows: 12
  .form-group
    = f.label :funding_history, "Any previous funding?"
    = f.text_area :funding_history, class: "form-control", rows: 3
  .form-group
    = f.label :milestones_and_funding_uses, "How do you intend to use the funding from the Innovation Fund?"
    = f.text_area :milestones_and_funding_uses, class: "form-control", rows: 3
  .form-group
    = f.label :risks, "What kinds of obstacles have you faced so far and what kinds of risks will you encounter in the future?"
    = f.text_area :risks, class: "form-control", rows: 12
  .form-group
    = f.submit 'Submit application', class: "button black"

app/views/applications/edit.html.haml
.container
  .row
    .col-sm-12
      %h1 Editing application
  .row
    .col-sm-8
      = render 'form'

      = link_to 'View application', @application, class: "button black"
      \|
      = link_to 'Back to all applications', applications_path, class: "button black"

app/views/applications/index.html.haml
.container
  .row
    .col-sm-12
      %h1 Listing applications

      %table.table.table-bordered
        %tr
          %th Id
          %th Company name
          %th Main contact email
        - @applications.each do |application|
          %tr
            %td= application.id
            %td= application.name
            %td= application.email
            %td= link_to 'View application', application
            %td= link_to 'Edit', edit_application_path(application)
            %td= link_to 'Delete', application, :method => :delete, :data => { :confirm => 'Are you sure?' }

      %br

      = link_to 'New Application', new_application_path, class: "button black"

app/views/applications/new.html.haml
%nav#navbars.navbar.navbar-default.navbar-fixed-top{role: "navigation"}
  / Brand and toggle get grouped for better mobile display
  .wrapper
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-ex1-collapse", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{href: "/", data: { no_turbolink: true }}
        -# %img.logo{alt: "logo", src: "images/logo.png"}>/
        Innovation Fund
    #navbar.collapse.navbar-collapse.navbar-ex1-collapse
      %ul.nav.navbar-nav.navbar-right
        %li
          %a{href: "/", data: { no_turbolink: true }} HOME
        %li
          %a.active{href: "#"} APPLICATION
.container.application-container
  .row
    .col-sm-12
      - if @application.errors.any?
        #error_explanation.alert.alert-danger
          %h2= "Oops looks like you have #{pluralize(@application.errors.count, "error")}, which stopped this application from being submitted."
          %ul
            - @application.errors.full_messages.each do |msg|
              %li= msg
      %h1 New application
      %h3 Judging Criteria
      %p Initial grants usually average 500-1000 dollars each. These grants are judged on the following criteria:
      %ul
        %li Projects must have an innovative factor: technological/process.
        %li Projects must have a technological component.
        %li Projects should have a good management team which is dedicated to implementation.
        %li Projects must be feasible.
        %li Projects must be in accordance with the Weiss Tech House ideals and mission.
        %li The innovative part of the project must be completed by the team and not outsourced.
      %p After the initial grant, teams can pitch once again for additional funding. These subsequent pitches are judged on the following criteria.
      %ul
        %li How has your team used the initial grant?
        %li What milestones has your team been able to reach with the initial grant?
        %li How does your team plan to use the additional funding?
        %li What milestones does your team plan to reach with the additional funding?
        %li What Tech House resources besides funding have your team utilized?
        %li Did your team stay in contact with your project manager and give him any project updates?
      %h3 Use of funds conditions:
      %p All proposed uses for the Innovation Fund grant must be initially approved by the team’s project manager and then ultimately by the entire Innovation Fund Committee. Common uses for Innovation Fund grants include:
      %ul
        %li Raw materials used to construct a prototype
        %li Server costs
        %li Necessary packaged software, but not the payment for a professional to write computer code
        %li Security certificates
  .row
    -# %h3 Online application form
    -# .col-sm-8
    -#   = render 'form'
    %h3 Application forms below:
    %p
      = link_to "Innovation Fund Main Application", "http://www.tech-house.upenn.edu/wp-content/uploads/2012/10/Innovation_Fund_Main_Application.doc"
    %p
      = link_to "Innovation Fund Executive Summary", "http://www.tech-house.upenn.edu/wp-content/uploads/2012/10/Innovation_Fund_Main_Application.doc"
    %p
      Additional instructions found in forms. If you have any additional questions contact us at
      %a{:href => "mailto:apply.innovationfund@gmail.com"} apply.innovationfund@gmail.com

    = link_to 'Back', root_path, data: { no_turbolink: true }, class: "button black"

app/views/applications/new_static.html.haml
%nav#navbars.navbar.navbar-default.navbar-fixed-top{role: "navigation"}
  / Brand and toggle get grouped for better mobile display
  .wrapper
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-ex1-collapse", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{href: "/", data: { no_turbolink: true }}
        -# %img.logo{alt: "logo", src: "images/logo.png"}>/
        Innovation Fund
    #navbar.collapse.navbar-collapse.navbar-ex1-collapse
      %ul.nav.navbar-nav.navbar-right
        %li
          %a{href: "/", data: { no_turbolink: true }} HOME
        %li
          %a.active{href: "#"} APPLICATION
.container.application-container
  .row
    .col-sm-12
      - if @application.errors.any?
        #error_explanation.alert.alert-danger
          %h2= "Oops looks like you have #{pluralize(@application.errors.count, "error")}, which stopped this application from being submitted."
          %ul
            - @application.errors.full_messages.each do |msg|
              %li= msg
      %h1 New application
      %h3 Judging Criteria
      %p Initial grants usually average 500-1000 dollars each. These grants are judged on the following criteria:
      %ul
        %li Projects must have an innovative factor: technological/process.
        %li Projects must have a technological component.
        %li Projects should have a good management team which is dedicated to implementation.
        %li Projects must be feasible.
        %li Projects must be in accordance with the Weiss Tech House ideals and mission.
        %li The innovative part of the project must be completed by the team and not outsourced.
      %p After the initial grant, teams can pitch once again for additional funding. These subsequent pitches are judged on the following criteria.
      %ul
        %li How has your team used the initial grant?
        %li What milestones has your team been able to reach with the initial grant?
        %li How does your team plan to use the additional funding?
        %li What milestones does your team plan to reach with the additional funding?
        %li What Tech House resources besides funding have your team utilized?
        %li Did your team stay in contact with your project manager and give him any project updates?
      %h3 Use of funds conditions:
      %p All proposed uses for the Innovation Fund grant must be initially approved by the team’s project manager and then ultimately by the entire Innovation Fund Committee. Common uses for Innovation Fund grants include:
      %ul
        %li Raw materials used to construct a prototype
        %li Server costs
        %li Necessary packaged software, but not the payment for a professional to write computer code
        %li Security certificates
  .row
    %h3 Application forms below:
    %p
      = link_to "Innovation Fund Main Application", "http://www.tech-house.upenn.edu/wp-content/uploads/2012/10/Innovation_Fund_Main_Application.doc"
    %p
      = link_to "Innovation Fund Executive Summary", "http://www.tech-house.upenn.edu/wp-content/uploads/2012/10/Innovation_Fund_Main_Application.doc"
    %p
      Additional instructions found in forms. If you have any additional questions contact us at
      %a{:href => "mailto:apply.innovationfund@gmail.com"} apply.innovationfund@gmail.com

    = link_to 'Back', root_path, data: { no_turbolink: true }, class: "button black"

app/views/applications/show.html.haml
.container
  .row
    .col-sm-8
      %p#notice= notice

      %p
        %b Video link:
        = @application.video_link
      %p
        %b Project summary:
        = @application.project_summary
      %p
        %b Problem:
        = @application.problem
      %p
        %b Solution:
        = @application.solution
      %p
        %b Name:
        = @application.name
      %p
        %b Email:
        = @application.email
      %p
        %b Funding history:
        = @application.funding_history
      %p
        %b Key financials:
        = @application.key_financials
      %p
        %b Team:
        = @application.team
      %p
        %b Target market:
        = @application.target_market
      %p
        %b Value proposition:
        = @application.value_proposition
      %p
        %b Technology:
        = @application.technology
      %p
        %b Competitive advantage:
        = @application.competitive_advantage
      %p
        %b Business model:
        = @application.business_model
      %p
        %b Milestones and funding uses:
        = @application.milestones_and_funding_uses
      %p
        %b Progress summary:
        = @application.progress_summary
      %p
        %b Team skills:
        = @application.team_skills
      %p
        %b Market analysis:
        = @application.market_analysis
      %p
        %b Risks:
        = @application.risks

      = link_to 'Edit application', edit_application_path(@application), class: "button black"
      \|
      = link_to 'Back to applications', applications_path, class: "button black"

app/views/layouts/application.haml
!!!
%html{lang: "en"}
  %head
    %meta{charset: "utf-8"}/
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %meta{content: "Innovation Fund at UPenn", name: "description"}/
    %title Innovation Fund | At the Weiss Tech House at the UPenn
    %script{src: "https://maps.google.com/maps/api/js?sensor=false&language=en", type: "text/javascript"}
    %link{:rel => "stylesheet", :href => "http://fonts.googleapis.com/css?family=Roboto+Slab:700,300,400"}
    %link{:rel => "stylesheet", :href => "http://fonts.googleapis.com/css?family=Bitter:400,400italic"}
    %link{:rel => "stylesheet", :href => "http://fonts.googleapis.com/css?family=Open+Sans:400,300,700"}
    %script
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    = yield